name: Teste no Commit

on:
  push:
    branches: [ "master" ]
  pull_request: 
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-and-deploy: 
    name: Executando o job de Teste
    runs-on: self-hosted
    
    steps: 
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Testando o workflow.

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: '<your-webapp-name>'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  test:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal