name: Workflow

on:
  push:
    branches: [ "master" ]
  pull_request: 
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test_job: 
    name: Executando o job de Teste
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Testando o workflow.
