name: Teste no Commit

on:
  push:
    branches: [ "master" ]
  pull_request: 
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-and-deploy: 
    name: Executando o job de Teste
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Testando o workflow.

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

  test:
    runs-on: self-hosted
    needs: build-and-deploy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Test database connection
      run: dotnet test --filter "Category=DatabaseIntegration" --no-restore --verbosity normal