name: Teste no Commit

on:
  push:
    branches: [ "master" ]
  pull_request: 
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-and-deploy: 
    name: Executando o job de Teste
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Testando o workflow.

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: | 
          dotnet build --configuration Release --no-restore
        continue-on-error: true  

      - name: Verificando sucesso do build
        run: |
          if [ $? -ne 0 ]; then
            echo "::error::Build failed."
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: dotnet restore

    - name: Run tests
      run: | 
        dotnet test --no-restore --verbosity normal
      continue-on-error: true

    - name: Check if tests passed
      run: |
        if [ $? -ne 0 ]; then
          echo "::error:: cFalha nos teste Automatizados."
          exit 1
        fi